# Default values for skaffold-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: hall-of-fame

service:
  name: go-app
  type: NodePort
  externalPort: 80
  internalPort: 8080